<?php


/**
 * @file
 * Site helpers for palisadeartlovers.org
 *
 */

/**
 * Implements hook_form_FORMID_alter().
 *
 * Alter the show_registration_node_form to hide the country field.
 */
function pals_site_form_show_registration_node_form_alter(&$form, &$form_state) {
  $form['field_entrant_address']['und'][0]['country']['#access'] = FALSE;
}

function pals_site_form_commerce_checkout_form_checkout_alter(&$form, &$form_state) {
  $form['account']['login']['mail']['#description'] = t('If you do not have an email account, please enter %email', array('%email' => variable_get('pals_site_default_email', 'janeellenjohnson@yahoo.com')));
  $form['account']['login']['mail_confirm'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('Please confirm your email address'),
    '#element_validate' => array('pals_site_commerce_checkout_email_validate'),
    '#default_value' => $form['account']['login']['mail']['#default_value'],
  );

  $form['customer_profile_billing']['commerce_customer_address']['und'][0]['country']['#access'] = FALSE;
}

/**
 * Validate that the two mail addresses match.
 */
function pals_site_commerce_checkout_email_validate($element, &$form_state, $form) {
  $login_state = $form_state['values']['account']['login'];
  if ($login_state['mail'] != $login_state['mail_confirm']) {
    form_error($element, t('Please check your confirmation email address.'));
  }
}

/**
* Implements hook_token_info_alter().
*
* Provide a "pals registration" token that is the rendered registration node.
*/
// function pals_site_token_info_alter(&$data) {
//   $data['tokens']['commerce-order']['pals-registration-url'] = array(
//     'name' => t('PALS Registration'),
//     'description' => t('Fully rendered node with PALS registration'),
//   );
// }

/**
 * Implements hook_tokens().
 *
 * Implement the pals-registration token.
 */
// function pals_site_tokens($type, $tokens, array $data = array(), array $options = array()) {
//   $url_options = array('absolute' => TRUE);

//   if (isset($options['language'])) {
//     $url_options['language'] = $options['language'];
//     $language_code = $options['language']->language;
//   }
//   else {
//     $language_code = NULL;
//   }

//   $sanitize = !empty($options['sanitize']);

//   $replacements = array();

//   if ($type == 'commerce-order' && !empty($data['commerce-order'])) {
//     $order = $data['commerce-order'];

//     foreach ($tokens as $name => $original) {
//       switch ($name) {
//         case 'pals-registration-url':
//           $reg_node = pals_site_get_reg_node($order);
//           $replacements[$original] = url('node/' . $reg_node->nid, array('absolute' => TRUE));
//           break;
//       }
//     }
//   }
//   return $replacements;
// }

/**
 * Get the rendered pals registration node.
 */
// function pals_site_get_reg_node($order) {

//   $wrapper = entity_metadata_wrapper('commerce_order', $order);

//   $rows = array();
//   foreach ($wrapper->commerce_line_items as $delta => $line_item_wrapper) {
//     if (!empty($line_item_wrapper->field_artshow_reg_info)) {
//       $reg_node = $line_item_wrapper->field_artshow_reg_info->value();
//       return $reg_node;
//     }
//   }


// }
