<?php


/**
 * @file
 * Site helpers for palisadeartlovers.org
 *
 */

/**
 * Implements hook_form_FORMID_alter().
 *
 * Alter the show_registration_node_form to hide the country field.
 */
function pals_site_form_show_registration_node_form_alter(&$form, &$form_state) {
  $form['field_entrant_address']['und'][0]['country']['#access'] = FALSE;
}

function pals_site_form_commerce_checkout_form_checkout_alter(&$form, &$form_state) {
  $form['account']['login']['mail']['#description'] = t('If you do not have an email account, please enter "nancy+noemail@nblewis.com"');
}
/**
 * Implements hook_form_alter().
 */
function pals_site_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id) {

  }
}



/**
* Implements hook_token_info_alter().
*
* Provide a "pals registration" token that is the rendered registration node.
*/
// function pals_site_token_info_alter(&$data) {
//   $data['tokens']['commerce-order']['pals-registration-url'] = array(
//     'name' => t('PALS Registration'),
//     'description' => t('Fully rendered node with PALS registration'),
//   );
// }

/**
 * Implements hook_tokens().
 *
 * Implement the pals-registration token.
 */
// function pals_site_tokens($type, $tokens, array $data = array(), array $options = array()) {
//   $url_options = array('absolute' => TRUE);

//   if (isset($options['language'])) {
//     $url_options['language'] = $options['language'];
//     $language_code = $options['language']->language;
//   }
//   else {
//     $language_code = NULL;
//   }

//   $sanitize = !empty($options['sanitize']);

//   $replacements = array();

//   if ($type == 'commerce-order' && !empty($data['commerce-order'])) {
//     $order = $data['commerce-order'];

//     foreach ($tokens as $name => $original) {
//       switch ($name) {
//         case 'pals-registration-url':
//           $reg_node = pals_site_get_reg_node($order);
//           $replacements[$original] = url('node/' . $reg_node->nid, array('absolute' => TRUE));
//           break;
//       }
//     }
//   }
//   return $replacements;
// }

/**
 * Get the rendered pals registration node.
 */
// function pals_site_get_reg_node($order) {

//   $wrapper = entity_metadata_wrapper('commerce_order', $order);

//   $rows = array();
//   foreach ($wrapper->commerce_line_items as $delta => $line_item_wrapper) {
//     if (!empty($line_item_wrapper->field_artshow_reg_info)) {
//       $reg_node = $line_item_wrapper->field_artshow_reg_info->value();
//       return $reg_node;
//     }
//   }


// }
